/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgsRouteImport } from './routes/orgs'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OrgsOrgSlugRouteImport } from './routes/orgs/$orgSlug'
import { Route as HomeLoginIndexRouteImport } from './routes/home/login/index'

const OrgsRoute = OrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OrgsOrgSlugRoute = OrgsOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => OrgsRoute,
} as any)
const HomeLoginIndexRoute = HomeLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/home': typeof HomeRouteWithChildren
  '/orgs': typeof OrgsRouteWithChildren
  '/orgs/$orgSlug': typeof OrgsOrgSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/home/login': typeof HomeLoginIndexRoute
}
export interface FileRoutesByTo {
  '/orgs': typeof OrgsRouteWithChildren
  '/orgs/$orgSlug': typeof OrgsOrgSlugRoute
  '/admin': typeof AdminIndexRoute
  '/home': typeof HomeIndexRoute
  '/home/login': typeof HomeLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteWithChildren
  '/home': typeof HomeRouteWithChildren
  '/orgs': typeof OrgsRouteWithChildren
  '/orgs/$orgSlug': typeof OrgsOrgSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/home/login/': typeof HomeLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/home'
    | '/orgs'
    | '/orgs/$orgSlug'
    | '/admin/'
    | '/home/'
    | '/home/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/orgs' | '/orgs/$orgSlug' | '/admin' | '/home' | '/home/login'
  id:
    | '__root__'
    | '/admin'
    | '/home'
    | '/orgs'
    | '/orgs/$orgSlug'
    | '/admin/'
    | '/home/'
    | '/home/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  HomeRoute: typeof HomeRouteWithChildren
  OrgsRoute: typeof OrgsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orgs': {
      id: '/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof OrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/orgs/$orgSlug': {
      id: '/orgs/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof OrgsOrgSlugRouteImport
      parentRoute: typeof OrgsRoute
    }
    '/home/login/': {
      id: '/home/login/'
      path: '/login'
      fullPath: '/home/login'
      preLoaderRoute: typeof HomeLoginIndexRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HomeRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeLoginIndexRoute: typeof HomeLoginIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeLoginIndexRoute: HomeLoginIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface OrgsRouteChildren {
  OrgsOrgSlugRoute: typeof OrgsOrgSlugRoute
}

const OrgsRouteChildren: OrgsRouteChildren = {
  OrgsOrgSlugRoute: OrgsOrgSlugRoute,
}

const OrgsRouteWithChildren = OrgsRoute._addFileChildren(OrgsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  HomeRoute: HomeRouteWithChildren,
  OrgsRoute: OrgsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
