version: "3.8"

services:
  start:
    container_name: sayr-start
    image: ghcr.io/dorasto/sayr-start:latest
    restart: always
    pull_policy: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DORAS_CLIENT_ID=${DORAS_CLIENT_ID}
      - DORAS_CLIENT_SECRET=${DORAS_CLIENT_SECRET}
      - VITE_URL_ROOT=${VITE_URL_ROOT}
      - VITE_PROJECT_NAME=${VITE_PROJECT_NAME}
      - VITE_WS_URL=${VITE_WS_URL}
      - VITE_ROOT_DOMAIN=${VITE_ROOT_DOMAIN}
      - VITE_EXTERNAL_API_URL=${VITE_EXTERNAL_API_URL}
      - STORAGE_URL=${STORAGE_URL}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
      - STORAGE_SECRET_KEY=${STORAGE_SECRET_KEY}
      - FILE_SALT=${FILE_SALT}
      - FILE_CDN=${FILE_CDN}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_APP_PRIVATE_KEY=${GITHUB_APP_PRIVATE_KEY}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - STORAGE_PORT=${STORAGE_PORT}
      - FILE_NAME_HASH_LENGTH=${FILE_NAME_HASH_LENGTH}
      - DORAS_ORGANIZATION=${DORAS_ORGANIZATION}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - VITE_SAYR_FRONTEND_AXIOM_TOKEN=${VITE_SAYR_FRONTEND_AXIOM_TOKEN}
      - VITE_SAYR_FRONTEND_AXIOM_DATASET=${VITE_SAYR_FRONTEND_AXIOM_DATASET}
      - VITE_TENOR_API=${VITE_TENOR_API}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - SYSTEM_ACCOUNT_ID=${SYSTEM_ACCOUNT_ID}
      - VITE_GITHUB_APP_NAME=${VITE_GITHUB_APP_NAME}
      - QUEUE_MODE=${QUEUE_MODE}
      - SAYR_EMAIL=${SAYR_EMAIL}
      - AXIOM_OTEL_TOKEN=${AXIOM_OTEL_TOKEN}
      - AXIOM_OTEL_DATASET=${AXIOM_OTEL_DATASET}
      - AXIOM_OTEL_DOMAIN=${AXIOM_OTEL_DOMAIN}
      - IS_CLOUD=${IS_CLOUD}
    networks:
      - app_network

  backend:
    container_name: sayr-backend
    image: ghcr.io/dorasto/sayr-backend:latest
    restart: always
    pull_policy: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DORAS_CLIENT_ID=${DORAS_CLIENT_ID}
      - DORAS_CLIENT_SECRET=${DORAS_CLIENT_SECRET}
      - NEXT_PUBLIC_URL_ROOT=${NEXT_PUBLIC_URL_ROOT}
      - NEXT_PUBLIC_API_SERVER=${NEXT_PUBLIC_API_SERVER}
      - NEXT_PUBLIC_PROJECT_NAME=${NEXT_PUBLIC_PROJECT_NAME}
      - STORAGE_URL=${STORAGE_URL}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
      - STORAGE_SECRET_KEY=${STORAGE_SECRET_KEY}
      - FILE_SALT=${FILE_SALT}
      - FILE_CDN=${FILE_CDN}
      - SAYR_EMAIL=${SAYR_EMAIL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_APP_PRIVATE_KEY=${GITHUB_APP_PRIVATE_KEY}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - STORAGE_PORT=${STORAGE_PORT}
      - FILE_NAME_HASH_LENGTH=${FILE_NAME_HASH_LENGTH}
      - DORAS_ORGANIZATION=${DORAS_ORGANIZATION}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - QUEUE_MODE=${QUEUE_MODE}
      - REDIS_URL=${REDIS_URL}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - SYSTEM_ACCOUNT_ID=${SYSTEM_ACCOUNT_ID}
      - AXIOM_OTEL_DOMAIN=${AXIOM_OTEL_DOMAIN}
      - AXIOM_OTEL_TOKEN=${AXIOM_OTEL_TOKEN}
      - AXIOM_OTEL_DATASET=${AXIOM_OTEL_DATASET}
      - IS_CLOUD=${IS_CLOUD}
    networks:
      - app_network

  github-worker:
    container_name: sayr-worker-github
    image: ghcr.io/dorasto/sayr-worker:latest
    restart: always
    pull_policy: always
    command: ["bun", "run", "dist/index.js", "github"]
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DORAS_CLIENT_ID=${DORAS_CLIENT_ID}
      - DORAS_CLIENT_SECRET=${DORAS_CLIENT_SECRET}
      - NEXT_PUBLIC_URL_ROOT=${NEXT_PUBLIC_URL_ROOT}
      - NEXT_PUBLIC_API_SERVER=${NEXT_PUBLIC_API_SERVER}
      - NEXT_PUBLIC_PROJECT_NAME=${NEXT_PUBLIC_PROJECT_NAME}
      - STORAGE_URL=${STORAGE_URL}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
      - STORAGE_SECRET_KEY=${STORAGE_SECRET_KEY}
      - FILE_SALT=${FILE_SALT}
      - FILE_CDN=${FILE_CDN}
      - SAYR_EMAIL=${SAYR_EMAIL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_APP_PRIVATE_KEY=${GITHUB_APP_PRIVATE_KEY}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - STORAGE_PORT=${STORAGE_PORT}
      - FILE_NAME_HASH_LENGTH=${FILE_NAME_HASH_LENGTH}
      - DORAS_ORGANIZATION=${DORAS_ORGANIZATION}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - QUEUE_MODE=${QUEUE_MODE}
      - REDIS_URL=${REDIS_URL}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - SYSTEM_ACCOUNT_ID=${SYSTEM_ACCOUNT_ID}
      - AXIOM_OTEL_DOMAIN=${AXIOM_OTEL_DOMAIN}
      - AXIOM_OTEL_TOKEN=${AXIOM_OTEL_TOKEN}
      - AXIOM_OTEL_DATASET=${AXIOM_OTEL_DATASET}
      - IS_CLOUD=${IS_CLOUD}
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: sayr-redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - app_network

  nginx:
    container_name: sayr-nginx
    image: ghcr.io/dorasto/sayr-nginx:latest
    restart: always
    pull_policy: always
    ports:
      - "3000:80"
    depends_on:
      - start
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
