/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProsekitTestRouteImport } from './routes/prosekit-test'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiImagePreviewRouteImport } from './routes/api/image-preview'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as AdminMineRouteRouteImport } from './routes/admin/mine/route'
import { Route as AdminOrgIdRouteRouteImport } from './routes/admin/$orgId/route'
import { Route as OrgsOrgSlugIndexRouteImport } from './routes/orgs/$orgSlug/index'
import { Route as InviteOrgIdIndexRouteImport } from './routes/invite/$orgId/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminMineIndexRouteImport } from './routes/admin/mine/index'
import { Route as AdminConsoleIndexRouteImport } from './routes/admin/console/index'
import { Route as AdminOrgIdIndexRouteImport } from './routes/admin/$orgId/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminSettingsConnectionsRouteRouteImport } from './routes/admin/settings/connections/route'
import { Route as AdminOrgIdTasksRouteRouteImport } from './routes/admin/$orgId/tasks/route'
import { Route as AdminSettingsConnectionsIndexRouteImport } from './routes/admin/settings/connections/index'
import { Route as AdminConsoleConnectionsIndexRouteImport } from './routes/admin/console/connections/index'
import { Route as AdminOrgIdTasksIndexRouteImport } from './routes/admin/$orgId/tasks/index'
import { Route as AdminSettingsOrgOrgIdRouteRouteImport } from './routes/admin/settings/org/$orgId/route'
import { Route as AdminOrgIdTasksTaskShortIdRouteRouteImport } from './routes/admin/$orgId/tasks/$taskShortId/route'
import { Route as AdminSettingsOrgOrgIdIndexRouteImport } from './routes/admin/settings/org/$orgId/index'
import { Route as AdminOrgIdTasksTaskShortIdIndexRouteImport } from './routes/admin/$orgId/tasks/$taskShortId/index'
import { Route as AdminSettingsOrgOrgIdViewsIndexRouteImport } from './routes/admin/settings/org/$orgId/views/index'
import { Route as AdminSettingsOrgOrgIdTeamsIndexRouteImport } from './routes/admin/settings/org/$orgId/teams/index'
import { Route as AdminSettingsOrgOrgIdMembersIndexRouteImport } from './routes/admin/settings/org/$orgId/members/index'
import { Route as AdminSettingsOrgOrgIdLabelsIndexRouteImport } from './routes/admin/settings/org/$orgId/labels/index'
import { Route as AdminSettingsOrgOrgIdConnectionsIndexRouteImport } from './routes/admin/settings/org/$orgId/connections/index'
import { Route as AdminSettingsOrgOrgIdCategoriesIndexRouteImport } from './routes/admin/settings/org/$orgId/categories/index'
import { Route as AdminSettingsOrgOrgIdViewsViewIdIndexRouteImport } from './routes/admin/settings/org/$orgId/views/$viewId/index'
import { Route as AdminSettingsOrgOrgIdTeamsTeamIdIndexRouteImport } from './routes/admin/settings/org/$orgId/teams/$teamId/index'
import { Route as AdminSettingsOrgOrgIdConnectionsConnectionIdIndexRouteImport } from './routes/admin/settings/org/$orgId/connections/$connectionId/index'

const ProsekitTestRoute = ProsekitTestRouteImport.update({
  id: '/prosekit-test',
  path: '/prosekit-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiImagePreviewRoute = ApiImagePreviewRouteImport.update({
  id: '/api/image-preview',
  path: '/api/image-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMineRouteRoute = AdminMineRouteRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrgIdRouteRoute = AdminOrgIdRouteRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrgsOrgSlugIndexRoute = OrgsOrgSlugIndexRouteImport.update({
  id: '/orgs/$orgSlug/',
  path: '/orgs/$orgSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteOrgIdIndexRoute = InviteOrgIdIndexRouteImport.update({
  id: '/invite/$orgId/',
  path: '/invite/$orgId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminMineIndexRoute = AdminMineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMineRouteRoute,
} as any)
const AdminConsoleIndexRoute = AdminConsoleIndexRouteImport.update({
  id: '/console/',
  path: '/console/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrgIdIndexRoute = AdminOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrgIdRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsConnectionsRouteRoute =
  AdminSettingsConnectionsRouteRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminOrgIdTasksRouteRoute = AdminOrgIdTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminOrgIdRouteRoute,
} as any)
const AdminSettingsConnectionsIndexRoute =
  AdminSettingsConnectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSettingsConnectionsRouteRoute,
  } as any)
const AdminConsoleConnectionsIndexRoute =
  AdminConsoleConnectionsIndexRouteImport.update({
    id: '/console/connections/',
    path: '/console/connections/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOrgIdTasksIndexRoute = AdminOrgIdTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrgIdTasksRouteRoute,
} as any)
const AdminSettingsOrgOrgIdRouteRoute =
  AdminSettingsOrgOrgIdRouteRouteImport.update({
    id: '/org/$orgId',
    path: '/org/$orgId',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminOrgIdTasksTaskShortIdRouteRoute =
  AdminOrgIdTasksTaskShortIdRouteRouteImport.update({
    id: '/$taskShortId',
    path: '/$taskShortId',
    getParentRoute: () => AdminOrgIdTasksRouteRoute,
  } as any)
const AdminSettingsOrgOrgIdIndexRoute =
  AdminSettingsOrgOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSettingsOrgOrgIdRouteRoute,
  } as any)
const AdminOrgIdTasksTaskShortIdIndexRoute =
  AdminOrgIdTasksTaskShortIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminOrgIdTasksTaskShortIdRouteRoute,
  } as any)
const AdminSettingsOrgOrgIdViewsIndexRoute =
  AdminSettingsOrgOrgIdViewsIndexRouteImport.update({
    id: '/views/',
    path: '/views/',
    getParentRoute: () => AdminSettingsOrgOrgIdRouteRoute,
  } as any)
const AdminSettingsOrgOrgIdTeamsIndexRoute =
  AdminSettingsOrgOrgIdTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => AdminSettingsOrgOrgIdRouteRoute,
  } as any)
const AdminSettingsOrgOrgIdMembersIndexRoute =
  AdminSettingsOrgOrgIdMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AdminSettingsOrgOrgIdRouteRoute,
  } as any)
const AdminSettingsOrgOrgIdLabelsIndexRoute =
  AdminSettingsOrgOrgIdLabelsIndexRouteImport.update({
    id: '/labels/',
    path: '/labels/',
    getParentRoute: () => AdminSettingsOrgOrgIdRouteRoute,
  } as any)
const AdminSettingsOrgOrgIdConnectionsIndexRoute =
  AdminSettingsOrgOrgIdConnectionsIndexRouteImport.update({
    id: '/connections/',
    path: '/connections/',
    getParentRoute: () => AdminSettingsOrgOrgIdRouteRoute,
  } as any)
const AdminSettingsOrgOrgIdCategoriesIndexRoute =
  AdminSettingsOrgOrgIdCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AdminSettingsOrgOrgIdRouteRoute,
  } as any)
const AdminSettingsOrgOrgIdViewsViewIdIndexRoute =
  AdminSettingsOrgOrgIdViewsViewIdIndexRouteImport.update({
    id: '/views/$viewId/',
    path: '/views/$viewId/',
    getParentRoute: () => AdminSettingsOrgOrgIdRouteRoute,
  } as any)
const AdminSettingsOrgOrgIdTeamsTeamIdIndexRoute =
  AdminSettingsOrgOrgIdTeamsTeamIdIndexRouteImport.update({
    id: '/teams/$teamId/',
    path: '/teams/$teamId/',
    getParentRoute: () => AdminSettingsOrgOrgIdRouteRoute,
  } as any)
const AdminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute =
  AdminSettingsOrgOrgIdConnectionsConnectionIdIndexRouteImport.update({
    id: '/connections/$connectionId/',
    path: '/connections/$connectionId/',
    getParentRoute: () => AdminSettingsOrgOrgIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/prosekit-test': typeof ProsekitTestRoute
  '/admin/$orgId': typeof AdminOrgIdRouteRouteWithChildren
  '/admin/mine': typeof AdminMineRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/api/image-preview': typeof ApiImagePreviewRoute
  '/admin/': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/admin/$orgId/tasks': typeof AdminOrgIdTasksRouteRouteWithChildren
  '/admin/settings/connections': typeof AdminSettingsConnectionsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/$orgId/': typeof AdminOrgIdIndexRoute
  '/admin/console': typeof AdminConsoleIndexRoute
  '/admin/mine/': typeof AdminMineIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/invite/$orgId': typeof InviteOrgIdIndexRoute
  '/orgs/$orgSlug': typeof OrgsOrgSlugIndexRoute
  '/admin/$orgId/tasks/$taskShortId': typeof AdminOrgIdTasksTaskShortIdRouteRouteWithChildren
  '/admin/settings/org/$orgId': typeof AdminSettingsOrgOrgIdRouteRouteWithChildren
  '/admin/$orgId/tasks/': typeof AdminOrgIdTasksIndexRoute
  '/admin/console/connections': typeof AdminConsoleConnectionsIndexRoute
  '/admin/settings/connections/': typeof AdminSettingsConnectionsIndexRoute
  '/admin/$orgId/tasks/$taskShortId/': typeof AdminOrgIdTasksTaskShortIdIndexRoute
  '/admin/settings/org/$orgId/': typeof AdminSettingsOrgOrgIdIndexRoute
  '/admin/settings/org/$orgId/categories': typeof AdminSettingsOrgOrgIdCategoriesIndexRoute
  '/admin/settings/org/$orgId/connections': typeof AdminSettingsOrgOrgIdConnectionsIndexRoute
  '/admin/settings/org/$orgId/labels': typeof AdminSettingsOrgOrgIdLabelsIndexRoute
  '/admin/settings/org/$orgId/members': typeof AdminSettingsOrgOrgIdMembersIndexRoute
  '/admin/settings/org/$orgId/teams': typeof AdminSettingsOrgOrgIdTeamsIndexRoute
  '/admin/settings/org/$orgId/views': typeof AdminSettingsOrgOrgIdViewsIndexRoute
  '/admin/settings/org/$orgId/connections/$connectionId': typeof AdminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute
  '/admin/settings/org/$orgId/teams/$teamId': typeof AdminSettingsOrgOrgIdTeamsTeamIdIndexRoute
  '/admin/settings/org/$orgId/views/$viewId': typeof AdminSettingsOrgOrgIdViewsViewIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prosekit-test': typeof ProsekitTestRoute
  '/api/image-preview': typeof ApiImagePreviewRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/$orgId': typeof AdminOrgIdIndexRoute
  '/admin/console': typeof AdminConsoleIndexRoute
  '/admin/mine': typeof AdminMineIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/invite/$orgId': typeof InviteOrgIdIndexRoute
  '/orgs/$orgSlug': typeof OrgsOrgSlugIndexRoute
  '/admin/$orgId/tasks': typeof AdminOrgIdTasksIndexRoute
  '/admin/console/connections': typeof AdminConsoleConnectionsIndexRoute
  '/admin/settings/connections': typeof AdminSettingsConnectionsIndexRoute
  '/admin/$orgId/tasks/$taskShortId': typeof AdminOrgIdTasksTaskShortIdIndexRoute
  '/admin/settings/org/$orgId': typeof AdminSettingsOrgOrgIdIndexRoute
  '/admin/settings/org/$orgId/categories': typeof AdminSettingsOrgOrgIdCategoriesIndexRoute
  '/admin/settings/org/$orgId/connections': typeof AdminSettingsOrgOrgIdConnectionsIndexRoute
  '/admin/settings/org/$orgId/labels': typeof AdminSettingsOrgOrgIdLabelsIndexRoute
  '/admin/settings/org/$orgId/members': typeof AdminSettingsOrgOrgIdMembersIndexRoute
  '/admin/settings/org/$orgId/teams': typeof AdminSettingsOrgOrgIdTeamsIndexRoute
  '/admin/settings/org/$orgId/views': typeof AdminSettingsOrgOrgIdViewsIndexRoute
  '/admin/settings/org/$orgId/connections/$connectionId': typeof AdminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute
  '/admin/settings/org/$orgId/teams/$teamId': typeof AdminSettingsOrgOrgIdTeamsTeamIdIndexRoute
  '/admin/settings/org/$orgId/views/$viewId': typeof AdminSettingsOrgOrgIdViewsViewIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/prosekit-test': typeof ProsekitTestRoute
  '/admin/$orgId': typeof AdminOrgIdRouteRouteWithChildren
  '/admin/mine': typeof AdminMineRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/api/image-preview': typeof ApiImagePreviewRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/admin/$orgId/tasks': typeof AdminOrgIdTasksRouteRouteWithChildren
  '/admin/settings/connections': typeof AdminSettingsConnectionsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/$orgId/': typeof AdminOrgIdIndexRoute
  '/admin/console/': typeof AdminConsoleIndexRoute
  '/admin/mine/': typeof AdminMineIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/invite/$orgId/': typeof InviteOrgIdIndexRoute
  '/orgs/$orgSlug/': typeof OrgsOrgSlugIndexRoute
  '/admin/$orgId/tasks/$taskShortId': typeof AdminOrgIdTasksTaskShortIdRouteRouteWithChildren
  '/admin/settings/org/$orgId': typeof AdminSettingsOrgOrgIdRouteRouteWithChildren
  '/admin/$orgId/tasks/': typeof AdminOrgIdTasksIndexRoute
  '/admin/console/connections/': typeof AdminConsoleConnectionsIndexRoute
  '/admin/settings/connections/': typeof AdminSettingsConnectionsIndexRoute
  '/admin/$orgId/tasks/$taskShortId/': typeof AdminOrgIdTasksTaskShortIdIndexRoute
  '/admin/settings/org/$orgId/': typeof AdminSettingsOrgOrgIdIndexRoute
  '/admin/settings/org/$orgId/categories/': typeof AdminSettingsOrgOrgIdCategoriesIndexRoute
  '/admin/settings/org/$orgId/connections/': typeof AdminSettingsOrgOrgIdConnectionsIndexRoute
  '/admin/settings/org/$orgId/labels/': typeof AdminSettingsOrgOrgIdLabelsIndexRoute
  '/admin/settings/org/$orgId/members/': typeof AdminSettingsOrgOrgIdMembersIndexRoute
  '/admin/settings/org/$orgId/teams/': typeof AdminSettingsOrgOrgIdTeamsIndexRoute
  '/admin/settings/org/$orgId/views/': typeof AdminSettingsOrgOrgIdViewsIndexRoute
  '/admin/settings/org/$orgId/connections/$connectionId/': typeof AdminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute
  '/admin/settings/org/$orgId/teams/$teamId/': typeof AdminSettingsOrgOrgIdTeamsTeamIdIndexRoute
  '/admin/settings/org/$orgId/views/$viewId/': typeof AdminSettingsOrgOrgIdViewsViewIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/prosekit-test'
    | '/admin/$orgId'
    | '/admin/mine'
    | '/admin/settings'
    | '/api/image-preview'
    | '/admin/'
    | '/login'
    | '/admin/$orgId/tasks'
    | '/admin/settings/connections'
    | '/api/auth/$'
    | '/admin/$orgId/'
    | '/admin/console'
    | '/admin/mine/'
    | '/admin/settings/'
    | '/invite/$orgId'
    | '/orgs/$orgSlug'
    | '/admin/$orgId/tasks/$taskShortId'
    | '/admin/settings/org/$orgId'
    | '/admin/$orgId/tasks/'
    | '/admin/console/connections'
    | '/admin/settings/connections/'
    | '/admin/$orgId/tasks/$taskShortId/'
    | '/admin/settings/org/$orgId/'
    | '/admin/settings/org/$orgId/categories'
    | '/admin/settings/org/$orgId/connections'
    | '/admin/settings/org/$orgId/labels'
    | '/admin/settings/org/$orgId/members'
    | '/admin/settings/org/$orgId/teams'
    | '/admin/settings/org/$orgId/views'
    | '/admin/settings/org/$orgId/connections/$connectionId'
    | '/admin/settings/org/$orgId/teams/$teamId'
    | '/admin/settings/org/$orgId/views/$viewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prosekit-test'
    | '/api/image-preview'
    | '/admin'
    | '/login'
    | '/api/auth/$'
    | '/admin/$orgId'
    | '/admin/console'
    | '/admin/mine'
    | '/admin/settings'
    | '/invite/$orgId'
    | '/orgs/$orgSlug'
    | '/admin/$orgId/tasks'
    | '/admin/console/connections'
    | '/admin/settings/connections'
    | '/admin/$orgId/tasks/$taskShortId'
    | '/admin/settings/org/$orgId'
    | '/admin/settings/org/$orgId/categories'
    | '/admin/settings/org/$orgId/connections'
    | '/admin/settings/org/$orgId/labels'
    | '/admin/settings/org/$orgId/members'
    | '/admin/settings/org/$orgId/teams'
    | '/admin/settings/org/$orgId/views'
    | '/admin/settings/org/$orgId/connections/$connectionId'
    | '/admin/settings/org/$orgId/teams/$teamId'
    | '/admin/settings/org/$orgId/views/$viewId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/prosekit-test'
    | '/admin/$orgId'
    | '/admin/mine'
    | '/admin/settings'
    | '/api/image-preview'
    | '/admin/'
    | '/login/'
    | '/admin/$orgId/tasks'
    | '/admin/settings/connections'
    | '/api/auth/$'
    | '/admin/$orgId/'
    | '/admin/console/'
    | '/admin/mine/'
    | '/admin/settings/'
    | '/invite/$orgId/'
    | '/orgs/$orgSlug/'
    | '/admin/$orgId/tasks/$taskShortId'
    | '/admin/settings/org/$orgId'
    | '/admin/$orgId/tasks/'
    | '/admin/console/connections/'
    | '/admin/settings/connections/'
    | '/admin/$orgId/tasks/$taskShortId/'
    | '/admin/settings/org/$orgId/'
    | '/admin/settings/org/$orgId/categories/'
    | '/admin/settings/org/$orgId/connections/'
    | '/admin/settings/org/$orgId/labels/'
    | '/admin/settings/org/$orgId/members/'
    | '/admin/settings/org/$orgId/teams/'
    | '/admin/settings/org/$orgId/views/'
    | '/admin/settings/org/$orgId/connections/$connectionId/'
    | '/admin/settings/org/$orgId/teams/$teamId/'
    | '/admin/settings/org/$orgId/views/$viewId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ProsekitTestRoute: typeof ProsekitTestRoute
  ApiImagePreviewRoute: typeof ApiImagePreviewRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  InviteOrgIdIndexRoute: typeof InviteOrgIdIndexRoute
  OrgsOrgSlugIndexRoute: typeof OrgsOrgSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prosekit-test': {
      id: '/prosekit-test'
      path: '/prosekit-test'
      fullPath: '/prosekit-test'
      preLoaderRoute: typeof ProsekitTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/image-preview': {
      id: '/api/image-preview'
      path: '/api/image-preview'
      fullPath: '/api/image-preview'
      preLoaderRoute: typeof ApiImagePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mine': {
      id: '/admin/mine'
      path: '/mine'
      fullPath: '/admin/mine'
      preLoaderRoute: typeof AdminMineRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$orgId': {
      id: '/admin/$orgId'
      path: '/$orgId'
      fullPath: '/admin/$orgId'
      preLoaderRoute: typeof AdminOrgIdRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/orgs/$orgSlug/': {
      id: '/orgs/$orgSlug/'
      path: '/orgs/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof OrgsOrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$orgId/': {
      id: '/invite/$orgId/'
      path: '/invite/$orgId'
      fullPath: '/invite/$orgId'
      preLoaderRoute: typeof InviteOrgIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/mine/': {
      id: '/admin/mine/'
      path: '/'
      fullPath: '/admin/mine/'
      preLoaderRoute: typeof AdminMineIndexRouteImport
      parentRoute: typeof AdminMineRouteRoute
    }
    '/admin/console/': {
      id: '/admin/console/'
      path: '/console'
      fullPath: '/admin/console'
      preLoaderRoute: typeof AdminConsoleIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$orgId/': {
      id: '/admin/$orgId/'
      path: '/'
      fullPath: '/admin/$orgId/'
      preLoaderRoute: typeof AdminOrgIdIndexRouteImport
      parentRoute: typeof AdminOrgIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/connections': {
      id: '/admin/settings/connections'
      path: '/connections'
      fullPath: '/admin/settings/connections'
      preLoaderRoute: typeof AdminSettingsConnectionsRouteRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/$orgId/tasks': {
      id: '/admin/$orgId/tasks'
      path: '/tasks'
      fullPath: '/admin/$orgId/tasks'
      preLoaderRoute: typeof AdminOrgIdTasksRouteRouteImport
      parentRoute: typeof AdminOrgIdRouteRoute
    }
    '/admin/settings/connections/': {
      id: '/admin/settings/connections/'
      path: '/'
      fullPath: '/admin/settings/connections/'
      preLoaderRoute: typeof AdminSettingsConnectionsIndexRouteImport
      parentRoute: typeof AdminSettingsConnectionsRouteRoute
    }
    '/admin/console/connections/': {
      id: '/admin/console/connections/'
      path: '/console/connections'
      fullPath: '/admin/console/connections'
      preLoaderRoute: typeof AdminConsoleConnectionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$orgId/tasks/': {
      id: '/admin/$orgId/tasks/'
      path: '/'
      fullPath: '/admin/$orgId/tasks/'
      preLoaderRoute: typeof AdminOrgIdTasksIndexRouteImport
      parentRoute: typeof AdminOrgIdTasksRouteRoute
    }
    '/admin/settings/org/$orgId': {
      id: '/admin/settings/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/admin/settings/org/$orgId'
      preLoaderRoute: typeof AdminSettingsOrgOrgIdRouteRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/$orgId/tasks/$taskShortId': {
      id: '/admin/$orgId/tasks/$taskShortId'
      path: '/$taskShortId'
      fullPath: '/admin/$orgId/tasks/$taskShortId'
      preLoaderRoute: typeof AdminOrgIdTasksTaskShortIdRouteRouteImport
      parentRoute: typeof AdminOrgIdTasksRouteRoute
    }
    '/admin/settings/org/$orgId/': {
      id: '/admin/settings/org/$orgId/'
      path: '/'
      fullPath: '/admin/settings/org/$orgId/'
      preLoaderRoute: typeof AdminSettingsOrgOrgIdIndexRouteImport
      parentRoute: typeof AdminSettingsOrgOrgIdRouteRoute
    }
    '/admin/$orgId/tasks/$taskShortId/': {
      id: '/admin/$orgId/tasks/$taskShortId/'
      path: '/'
      fullPath: '/admin/$orgId/tasks/$taskShortId/'
      preLoaderRoute: typeof AdminOrgIdTasksTaskShortIdIndexRouteImport
      parentRoute: typeof AdminOrgIdTasksTaskShortIdRouteRoute
    }
    '/admin/settings/org/$orgId/views/': {
      id: '/admin/settings/org/$orgId/views/'
      path: '/views'
      fullPath: '/admin/settings/org/$orgId/views'
      preLoaderRoute: typeof AdminSettingsOrgOrgIdViewsIndexRouteImport
      parentRoute: typeof AdminSettingsOrgOrgIdRouteRoute
    }
    '/admin/settings/org/$orgId/teams/': {
      id: '/admin/settings/org/$orgId/teams/'
      path: '/teams'
      fullPath: '/admin/settings/org/$orgId/teams'
      preLoaderRoute: typeof AdminSettingsOrgOrgIdTeamsIndexRouteImport
      parentRoute: typeof AdminSettingsOrgOrgIdRouteRoute
    }
    '/admin/settings/org/$orgId/members/': {
      id: '/admin/settings/org/$orgId/members/'
      path: '/members'
      fullPath: '/admin/settings/org/$orgId/members'
      preLoaderRoute: typeof AdminSettingsOrgOrgIdMembersIndexRouteImport
      parentRoute: typeof AdminSettingsOrgOrgIdRouteRoute
    }
    '/admin/settings/org/$orgId/labels/': {
      id: '/admin/settings/org/$orgId/labels/'
      path: '/labels'
      fullPath: '/admin/settings/org/$orgId/labels'
      preLoaderRoute: typeof AdminSettingsOrgOrgIdLabelsIndexRouteImport
      parentRoute: typeof AdminSettingsOrgOrgIdRouteRoute
    }
    '/admin/settings/org/$orgId/connections/': {
      id: '/admin/settings/org/$orgId/connections/'
      path: '/connections'
      fullPath: '/admin/settings/org/$orgId/connections'
      preLoaderRoute: typeof AdminSettingsOrgOrgIdConnectionsIndexRouteImport
      parentRoute: typeof AdminSettingsOrgOrgIdRouteRoute
    }
    '/admin/settings/org/$orgId/categories/': {
      id: '/admin/settings/org/$orgId/categories/'
      path: '/categories'
      fullPath: '/admin/settings/org/$orgId/categories'
      preLoaderRoute: typeof AdminSettingsOrgOrgIdCategoriesIndexRouteImport
      parentRoute: typeof AdminSettingsOrgOrgIdRouteRoute
    }
    '/admin/settings/org/$orgId/views/$viewId/': {
      id: '/admin/settings/org/$orgId/views/$viewId/'
      path: '/views/$viewId'
      fullPath: '/admin/settings/org/$orgId/views/$viewId'
      preLoaderRoute: typeof AdminSettingsOrgOrgIdViewsViewIdIndexRouteImport
      parentRoute: typeof AdminSettingsOrgOrgIdRouteRoute
    }
    '/admin/settings/org/$orgId/teams/$teamId/': {
      id: '/admin/settings/org/$orgId/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/admin/settings/org/$orgId/teams/$teamId'
      preLoaderRoute: typeof AdminSettingsOrgOrgIdTeamsTeamIdIndexRouteImport
      parentRoute: typeof AdminSettingsOrgOrgIdRouteRoute
    }
    '/admin/settings/org/$orgId/connections/$connectionId/': {
      id: '/admin/settings/org/$orgId/connections/$connectionId/'
      path: '/connections/$connectionId'
      fullPath: '/admin/settings/org/$orgId/connections/$connectionId'
      preLoaderRoute: typeof AdminSettingsOrgOrgIdConnectionsConnectionIdIndexRouteImport
      parentRoute: typeof AdminSettingsOrgOrgIdRouteRoute
    }
  }
}

interface AdminOrgIdTasksTaskShortIdRouteRouteChildren {
  AdminOrgIdTasksTaskShortIdIndexRoute: typeof AdminOrgIdTasksTaskShortIdIndexRoute
}

const AdminOrgIdTasksTaskShortIdRouteRouteChildren: AdminOrgIdTasksTaskShortIdRouteRouteChildren =
  {
    AdminOrgIdTasksTaskShortIdIndexRoute: AdminOrgIdTasksTaskShortIdIndexRoute,
  }

const AdminOrgIdTasksTaskShortIdRouteRouteWithChildren =
  AdminOrgIdTasksTaskShortIdRouteRoute._addFileChildren(
    AdminOrgIdTasksTaskShortIdRouteRouteChildren,
  )

interface AdminOrgIdTasksRouteRouteChildren {
  AdminOrgIdTasksTaskShortIdRouteRoute: typeof AdminOrgIdTasksTaskShortIdRouteRouteWithChildren
  AdminOrgIdTasksIndexRoute: typeof AdminOrgIdTasksIndexRoute
}

const AdminOrgIdTasksRouteRouteChildren: AdminOrgIdTasksRouteRouteChildren = {
  AdminOrgIdTasksTaskShortIdRouteRoute:
    AdminOrgIdTasksTaskShortIdRouteRouteWithChildren,
  AdminOrgIdTasksIndexRoute: AdminOrgIdTasksIndexRoute,
}

const AdminOrgIdTasksRouteRouteWithChildren =
  AdminOrgIdTasksRouteRoute._addFileChildren(AdminOrgIdTasksRouteRouteChildren)

interface AdminOrgIdRouteRouteChildren {
  AdminOrgIdTasksRouteRoute: typeof AdminOrgIdTasksRouteRouteWithChildren
  AdminOrgIdIndexRoute: typeof AdminOrgIdIndexRoute
}

const AdminOrgIdRouteRouteChildren: AdminOrgIdRouteRouteChildren = {
  AdminOrgIdTasksRouteRoute: AdminOrgIdTasksRouteRouteWithChildren,
  AdminOrgIdIndexRoute: AdminOrgIdIndexRoute,
}

const AdminOrgIdRouteRouteWithChildren = AdminOrgIdRouteRoute._addFileChildren(
  AdminOrgIdRouteRouteChildren,
)

interface AdminMineRouteRouteChildren {
  AdminMineIndexRoute: typeof AdminMineIndexRoute
}

const AdminMineRouteRouteChildren: AdminMineRouteRouteChildren = {
  AdminMineIndexRoute: AdminMineIndexRoute,
}

const AdminMineRouteRouteWithChildren = AdminMineRouteRoute._addFileChildren(
  AdminMineRouteRouteChildren,
)

interface AdminSettingsConnectionsRouteRouteChildren {
  AdminSettingsConnectionsIndexRoute: typeof AdminSettingsConnectionsIndexRoute
}

const AdminSettingsConnectionsRouteRouteChildren: AdminSettingsConnectionsRouteRouteChildren =
  {
    AdminSettingsConnectionsIndexRoute: AdminSettingsConnectionsIndexRoute,
  }

const AdminSettingsConnectionsRouteRouteWithChildren =
  AdminSettingsConnectionsRouteRoute._addFileChildren(
    AdminSettingsConnectionsRouteRouteChildren,
  )

interface AdminSettingsOrgOrgIdRouteRouteChildren {
  AdminSettingsOrgOrgIdIndexRoute: typeof AdminSettingsOrgOrgIdIndexRoute
  AdminSettingsOrgOrgIdCategoriesIndexRoute: typeof AdminSettingsOrgOrgIdCategoriesIndexRoute
  AdminSettingsOrgOrgIdConnectionsIndexRoute: typeof AdminSettingsOrgOrgIdConnectionsIndexRoute
  AdminSettingsOrgOrgIdLabelsIndexRoute: typeof AdminSettingsOrgOrgIdLabelsIndexRoute
  AdminSettingsOrgOrgIdMembersIndexRoute: typeof AdminSettingsOrgOrgIdMembersIndexRoute
  AdminSettingsOrgOrgIdTeamsIndexRoute: typeof AdminSettingsOrgOrgIdTeamsIndexRoute
  AdminSettingsOrgOrgIdViewsIndexRoute: typeof AdminSettingsOrgOrgIdViewsIndexRoute
  AdminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute: typeof AdminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute
  AdminSettingsOrgOrgIdTeamsTeamIdIndexRoute: typeof AdminSettingsOrgOrgIdTeamsTeamIdIndexRoute
  AdminSettingsOrgOrgIdViewsViewIdIndexRoute: typeof AdminSettingsOrgOrgIdViewsViewIdIndexRoute
}

const AdminSettingsOrgOrgIdRouteRouteChildren: AdminSettingsOrgOrgIdRouteRouteChildren =
  {
    AdminSettingsOrgOrgIdIndexRoute: AdminSettingsOrgOrgIdIndexRoute,
    AdminSettingsOrgOrgIdCategoriesIndexRoute:
      AdminSettingsOrgOrgIdCategoriesIndexRoute,
    AdminSettingsOrgOrgIdConnectionsIndexRoute:
      AdminSettingsOrgOrgIdConnectionsIndexRoute,
    AdminSettingsOrgOrgIdLabelsIndexRoute:
      AdminSettingsOrgOrgIdLabelsIndexRoute,
    AdminSettingsOrgOrgIdMembersIndexRoute:
      AdminSettingsOrgOrgIdMembersIndexRoute,
    AdminSettingsOrgOrgIdTeamsIndexRoute: AdminSettingsOrgOrgIdTeamsIndexRoute,
    AdminSettingsOrgOrgIdViewsIndexRoute: AdminSettingsOrgOrgIdViewsIndexRoute,
    AdminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute:
      AdminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute,
    AdminSettingsOrgOrgIdTeamsTeamIdIndexRoute:
      AdminSettingsOrgOrgIdTeamsTeamIdIndexRoute,
    AdminSettingsOrgOrgIdViewsViewIdIndexRoute:
      AdminSettingsOrgOrgIdViewsViewIdIndexRoute,
  }

const AdminSettingsOrgOrgIdRouteRouteWithChildren =
  AdminSettingsOrgOrgIdRouteRoute._addFileChildren(
    AdminSettingsOrgOrgIdRouteRouteChildren,
  )

interface AdminSettingsRouteRouteChildren {
  AdminSettingsConnectionsRouteRoute: typeof AdminSettingsConnectionsRouteRouteWithChildren
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminSettingsOrgOrgIdRouteRoute: typeof AdminSettingsOrgOrgIdRouteRouteWithChildren
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsConnectionsRouteRoute:
    AdminSettingsConnectionsRouteRouteWithChildren,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminSettingsOrgOrgIdRouteRoute: AdminSettingsOrgOrgIdRouteRouteWithChildren,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminOrgIdRouteRoute: typeof AdminOrgIdRouteRouteWithChildren
  AdminMineRouteRoute: typeof AdminMineRouteRouteWithChildren
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConsoleIndexRoute: typeof AdminConsoleIndexRoute
  AdminConsoleConnectionsIndexRoute: typeof AdminConsoleConnectionsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminOrgIdRouteRoute: AdminOrgIdRouteRouteWithChildren,
  AdminMineRouteRoute: AdminMineRouteRouteWithChildren,
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminConsoleIndexRoute: AdminConsoleIndexRoute,
  AdminConsoleConnectionsIndexRoute: AdminConsoleConnectionsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ProsekitTestRoute: ProsekitTestRoute,
  ApiImagePreviewRoute: ApiImagePreviewRoute,
  LoginIndexRoute: LoginIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  InviteOrgIdIndexRoute: InviteOrgIdIndexRoute,
  OrgsOrgSlugIndexRoute: OrgsOrgSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
