/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OrgsOrgSlugRouteImport } from './routes/orgs/$orgSlug'
import { Route as HomeLoginIndexRouteImport } from './routes/home/login/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrgsOrgSlugRoute = OrgsOrgSlugRouteImport.update({
  id: '/orgs/$orgSlug',
  path: '/orgs/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLoginIndexRoute = HomeLoginIndexRouteImport.update({
  id: '/home/login/',
  path: '/home/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/orgs/$orgSlug': typeof OrgsOrgSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/home': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/home/login': typeof HomeLoginIndexRoute
}
export interface FileRoutesByTo {
  '/orgs/$orgSlug': typeof OrgsOrgSlugRoute
  '/admin': typeof AdminIndexRoute
  '/home': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/home/login': typeof HomeLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/orgs/$orgSlug': typeof OrgsOrgSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/home/login/': typeof HomeLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/orgs/$orgSlug'
    | '/admin/'
    | '/home'
    | '/api/auth/$'
    | '/home/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/orgs/$orgSlug' | '/admin' | '/home' | '/api/auth/$' | '/home/login'
  id:
    | '__root__'
    | '/admin'
    | '/orgs/$orgSlug'
    | '/admin/'
    | '/home/'
    | '/api/auth/$'
    | '/home/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  OrgsOrgSlugRoute: typeof OrgsOrgSlugRoute
  HomeIndexRoute: typeof HomeIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  HomeLoginIndexRoute: typeof HomeLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/orgs/$orgSlug': {
      id: '/orgs/$orgSlug'
      path: '/orgs/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof OrgsOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/login/': {
      id: '/home/login/'
      path: '/home/login'
      fullPath: '/home/login'
      preLoaderRoute: typeof HomeLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  OrgsOrgSlugRoute: OrgsOrgSlugRoute,
  HomeIndexRoute: HomeIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  HomeLoginIndexRoute: HomeLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
