/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProsekitTestRouteImport } from './routes/prosekit-test'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as adminIndexRouteImport } from './routes/(admin)/index'
import { Route as LoginAuthCheckRouteImport } from './routes/login/auth-check'
import { Route as ApiImagePreviewRouteImport } from './routes/api/image-preview'
import { Route as adminSettingsRouteRouteImport } from './routes/(admin)/settings/route'
import { Route as adminMineRouteRouteImport } from './routes/(admin)/mine/route'
import { Route as adminOrgIdRouteRouteImport } from './routes/(admin)/$orgId/route'
import { Route as OrgsOrgSlugIndexRouteImport } from './routes/orgs/$orgSlug/index'
import { Route as InviteOrgIdIndexRouteImport } from './routes/invite/$orgId/index'
import { Route as adminSettingsIndexRouteImport } from './routes/(admin)/settings/index'
import { Route as adminMineIndexRouteImport } from './routes/(admin)/mine/index'
import { Route as adminConsoleIndexRouteImport } from './routes/(admin)/console/index'
import { Route as adminOrgIdIndexRouteImport } from './routes/(admin)/$orgId/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as adminSettingsConnectionsRouteRouteImport } from './routes/(admin)/settings/connections/route'
import { Route as adminOrgIdTasksRouteRouteImport } from './routes/(admin)/$orgId/tasks/route'
import { Route as adminSettingsConnectionsIndexRouteImport } from './routes/(admin)/settings/connections/index'
import { Route as adminConsoleConnectionsIndexRouteImport } from './routes/(admin)/console/connections/index'
import { Route as adminOrgIdTasksIndexRouteImport } from './routes/(admin)/$orgId/tasks/index'
import { Route as adminSettingsOrgOrgIdRouteRouteImport } from './routes/(admin)/settings/org/$orgId/route'
import { Route as adminOrgIdTasksTaskShortIdRouteRouteImport } from './routes/(admin)/$orgId/tasks/$taskShortId/route'
import { Route as adminSettingsOrgOrgIdIndexRouteImport } from './routes/(admin)/settings/org/$orgId/index'
import { Route as adminOrgIdTasksTaskShortIdIndexRouteImport } from './routes/(admin)/$orgId/tasks/$taskShortId/index'
import { Route as adminSettingsOrgOrgIdViewsIndexRouteImport } from './routes/(admin)/settings/org/$orgId/views/index'
import { Route as adminSettingsOrgOrgIdTemplatesIndexRouteImport } from './routes/(admin)/settings/org/$orgId/templates/index'
import { Route as adminSettingsOrgOrgIdTeamsIndexRouteImport } from './routes/(admin)/settings/org/$orgId/teams/index'
import { Route as adminSettingsOrgOrgIdMembersIndexRouteImport } from './routes/(admin)/settings/org/$orgId/members/index'
import { Route as adminSettingsOrgOrgIdLabelsIndexRouteImport } from './routes/(admin)/settings/org/$orgId/labels/index'
import { Route as adminSettingsOrgOrgIdConnectionsIndexRouteImport } from './routes/(admin)/settings/org/$orgId/connections/index'
import { Route as adminSettingsOrgOrgIdCategoriesIndexRouteImport } from './routes/(admin)/settings/org/$orgId/categories/index'
import { Route as adminSettingsOrgOrgIdTeamsNewRouteImport } from './routes/(admin)/settings/org/$orgId/teams/new'
import { Route as adminSettingsOrgOrgIdViewsViewIdIndexRouteImport } from './routes/(admin)/settings/org/$orgId/views/$viewId/index'
import { Route as adminSettingsOrgOrgIdTeamsTeamIdIndexRouteImport } from './routes/(admin)/settings/org/$orgId/teams/$teamId/index'
import { Route as adminSettingsOrgOrgIdConnectionsConnectionIdIndexRouteImport } from './routes/(admin)/settings/org/$orgId/connections/$connectionId/index'

const ProsekitTestRoute = ProsekitTestRouteImport.update({
  id: '/prosekit-test',
  path: '/prosekit-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminIndexRoute = adminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminRouteRoute,
} as any)
const LoginAuthCheckRoute = LoginAuthCheckRouteImport.update({
  id: '/login/auth-check',
  path: '/login/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagePreviewRoute = ApiImagePreviewRouteImport.update({
  id: '/api/image-preview',
  path: '/api/image-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSettingsRouteRoute = adminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminMineRouteRoute = adminMineRouteRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminOrgIdRouteRoute = adminOrgIdRouteRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => adminRouteRoute,
} as any)
const OrgsOrgSlugIndexRoute = OrgsOrgSlugIndexRouteImport.update({
  id: '/orgs/$orgSlug/',
  path: '/orgs/$orgSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteOrgIdIndexRoute = InviteOrgIdIndexRouteImport.update({
  id: '/invite/$orgId/',
  path: '/invite/$orgId/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSettingsIndexRoute = adminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminSettingsRouteRoute,
} as any)
const adminMineIndexRoute = adminMineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminMineRouteRoute,
} as any)
const adminConsoleIndexRoute = adminConsoleIndexRouteImport.update({
  id: '/console/',
  path: '/console/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminOrgIdIndexRoute = adminOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminOrgIdRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSettingsConnectionsRouteRoute =
  adminSettingsConnectionsRouteRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => adminSettingsRouteRoute,
  } as any)
const adminOrgIdTasksRouteRoute = adminOrgIdTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => adminOrgIdRouteRoute,
} as any)
const adminSettingsConnectionsIndexRoute =
  adminSettingsConnectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => adminSettingsConnectionsRouteRoute,
  } as any)
const adminConsoleConnectionsIndexRoute =
  adminConsoleConnectionsIndexRouteImport.update({
    id: '/console/connections/',
    path: '/console/connections/',
    getParentRoute: () => adminRouteRoute,
  } as any)
const adminOrgIdTasksIndexRoute = adminOrgIdTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminOrgIdTasksRouteRoute,
} as any)
const adminSettingsOrgOrgIdRouteRoute =
  adminSettingsOrgOrgIdRouteRouteImport.update({
    id: '/org/$orgId',
    path: '/org/$orgId',
    getParentRoute: () => adminSettingsRouteRoute,
  } as any)
const adminOrgIdTasksTaskShortIdRouteRoute =
  adminOrgIdTasksTaskShortIdRouteRouteImport.update({
    id: '/$taskShortId',
    path: '/$taskShortId',
    getParentRoute: () => adminOrgIdTasksRouteRoute,
  } as any)
const adminSettingsOrgOrgIdIndexRoute =
  adminSettingsOrgOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => adminSettingsOrgOrgIdRouteRoute,
  } as any)
const adminOrgIdTasksTaskShortIdIndexRoute =
  adminOrgIdTasksTaskShortIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => adminOrgIdTasksTaskShortIdRouteRoute,
  } as any)
const adminSettingsOrgOrgIdViewsIndexRoute =
  adminSettingsOrgOrgIdViewsIndexRouteImport.update({
    id: '/views/',
    path: '/views/',
    getParentRoute: () => adminSettingsOrgOrgIdRouteRoute,
  } as any)
const adminSettingsOrgOrgIdTemplatesIndexRoute =
  adminSettingsOrgOrgIdTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => adminSettingsOrgOrgIdRouteRoute,
  } as any)
const adminSettingsOrgOrgIdTeamsIndexRoute =
  adminSettingsOrgOrgIdTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => adminSettingsOrgOrgIdRouteRoute,
  } as any)
const adminSettingsOrgOrgIdMembersIndexRoute =
  adminSettingsOrgOrgIdMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => adminSettingsOrgOrgIdRouteRoute,
  } as any)
const adminSettingsOrgOrgIdLabelsIndexRoute =
  adminSettingsOrgOrgIdLabelsIndexRouteImport.update({
    id: '/labels/',
    path: '/labels/',
    getParentRoute: () => adminSettingsOrgOrgIdRouteRoute,
  } as any)
const adminSettingsOrgOrgIdConnectionsIndexRoute =
  adminSettingsOrgOrgIdConnectionsIndexRouteImport.update({
    id: '/connections/',
    path: '/connections/',
    getParentRoute: () => adminSettingsOrgOrgIdRouteRoute,
  } as any)
const adminSettingsOrgOrgIdCategoriesIndexRoute =
  adminSettingsOrgOrgIdCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => adminSettingsOrgOrgIdRouteRoute,
  } as any)
const adminSettingsOrgOrgIdTeamsNewRoute =
  adminSettingsOrgOrgIdTeamsNewRouteImport.update({
    id: '/teams/new',
    path: '/teams/new',
    getParentRoute: () => adminSettingsOrgOrgIdRouteRoute,
  } as any)
const adminSettingsOrgOrgIdViewsViewIdIndexRoute =
  adminSettingsOrgOrgIdViewsViewIdIndexRouteImport.update({
    id: '/views/$viewId/',
    path: '/views/$viewId/',
    getParentRoute: () => adminSettingsOrgOrgIdRouteRoute,
  } as any)
const adminSettingsOrgOrgIdTeamsTeamIdIndexRoute =
  adminSettingsOrgOrgIdTeamsTeamIdIndexRouteImport.update({
    id: '/teams/$teamId/',
    path: '/teams/$teamId/',
    getParentRoute: () => adminSettingsOrgOrgIdRouteRoute,
  } as any)
const adminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute =
  adminSettingsOrgOrgIdConnectionsConnectionIdIndexRouteImport.update({
    id: '/connections/$connectionId/',
    path: '/connections/$connectionId/',
    getParentRoute: () => adminSettingsOrgOrgIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/prosekit-test': typeof ProsekitTestRoute
  '/$orgId': typeof adminOrgIdRouteRouteWithChildren
  '/mine': typeof adminMineRouteRouteWithChildren
  '/settings': typeof adminSettingsRouteRouteWithChildren
  '/api/image-preview': typeof ApiImagePreviewRoute
  '/login/auth-check': typeof LoginAuthCheckRoute
  '/': typeof adminIndexRoute
  '/login': typeof LoginIndexRoute
  '/$orgId/tasks': typeof adminOrgIdTasksRouteRouteWithChildren
  '/settings/connections': typeof adminSettingsConnectionsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$orgId/': typeof adminOrgIdIndexRoute
  '/console': typeof adminConsoleIndexRoute
  '/mine/': typeof adminMineIndexRoute
  '/settings/': typeof adminSettingsIndexRoute
  '/invite/$orgId': typeof InviteOrgIdIndexRoute
  '/orgs/$orgSlug': typeof OrgsOrgSlugIndexRoute
  '/$orgId/tasks/$taskShortId': typeof adminOrgIdTasksTaskShortIdRouteRouteWithChildren
  '/settings/org/$orgId': typeof adminSettingsOrgOrgIdRouteRouteWithChildren
  '/$orgId/tasks/': typeof adminOrgIdTasksIndexRoute
  '/console/connections': typeof adminConsoleConnectionsIndexRoute
  '/settings/connections/': typeof adminSettingsConnectionsIndexRoute
  '/$orgId/tasks/$taskShortId/': typeof adminOrgIdTasksTaskShortIdIndexRoute
  '/settings/org/$orgId/': typeof adminSettingsOrgOrgIdIndexRoute
  '/settings/org/$orgId/teams/new': typeof adminSettingsOrgOrgIdTeamsNewRoute
  '/settings/org/$orgId/categories': typeof adminSettingsOrgOrgIdCategoriesIndexRoute
  '/settings/org/$orgId/connections': typeof adminSettingsOrgOrgIdConnectionsIndexRoute
  '/settings/org/$orgId/labels': typeof adminSettingsOrgOrgIdLabelsIndexRoute
  '/settings/org/$orgId/members': typeof adminSettingsOrgOrgIdMembersIndexRoute
  '/settings/org/$orgId/teams': typeof adminSettingsOrgOrgIdTeamsIndexRoute
  '/settings/org/$orgId/templates': typeof adminSettingsOrgOrgIdTemplatesIndexRoute
  '/settings/org/$orgId/views': typeof adminSettingsOrgOrgIdViewsIndexRoute
  '/settings/org/$orgId/connections/$connectionId': typeof adminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute
  '/settings/org/$orgId/teams/$teamId': typeof adminSettingsOrgOrgIdTeamsTeamIdIndexRoute
  '/settings/org/$orgId/views/$viewId': typeof adminSettingsOrgOrgIdViewsViewIdIndexRoute
}
export interface FileRoutesByTo {
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/prosekit-test': typeof ProsekitTestRoute
  '/api/image-preview': typeof ApiImagePreviewRoute
  '/login/auth-check': typeof LoginAuthCheckRoute
  '/': typeof adminIndexRoute
  '/login': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$orgId': typeof adminOrgIdIndexRoute
  '/console': typeof adminConsoleIndexRoute
  '/mine': typeof adminMineIndexRoute
  '/settings': typeof adminSettingsIndexRoute
  '/invite/$orgId': typeof InviteOrgIdIndexRoute
  '/orgs/$orgSlug': typeof OrgsOrgSlugIndexRoute
  '/$orgId/tasks': typeof adminOrgIdTasksIndexRoute
  '/console/connections': typeof adminConsoleConnectionsIndexRoute
  '/settings/connections': typeof adminSettingsConnectionsIndexRoute
  '/$orgId/tasks/$taskShortId': typeof adminOrgIdTasksTaskShortIdIndexRoute
  '/settings/org/$orgId': typeof adminSettingsOrgOrgIdIndexRoute
  '/settings/org/$orgId/teams/new': typeof adminSettingsOrgOrgIdTeamsNewRoute
  '/settings/org/$orgId/categories': typeof adminSettingsOrgOrgIdCategoriesIndexRoute
  '/settings/org/$orgId/connections': typeof adminSettingsOrgOrgIdConnectionsIndexRoute
  '/settings/org/$orgId/labels': typeof adminSettingsOrgOrgIdLabelsIndexRoute
  '/settings/org/$orgId/members': typeof adminSettingsOrgOrgIdMembersIndexRoute
  '/settings/org/$orgId/teams': typeof adminSettingsOrgOrgIdTeamsIndexRoute
  '/settings/org/$orgId/templates': typeof adminSettingsOrgOrgIdTemplatesIndexRoute
  '/settings/org/$orgId/views': typeof adminSettingsOrgOrgIdViewsIndexRoute
  '/settings/org/$orgId/connections/$connectionId': typeof adminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute
  '/settings/org/$orgId/teams/$teamId': typeof adminSettingsOrgOrgIdTeamsTeamIdIndexRoute
  '/settings/org/$orgId/views/$viewId': typeof adminSettingsOrgOrgIdViewsViewIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)': typeof adminRouteRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/prosekit-test': typeof ProsekitTestRoute
  '/(admin)/$orgId': typeof adminOrgIdRouteRouteWithChildren
  '/(admin)/mine': typeof adminMineRouteRouteWithChildren
  '/(admin)/settings': typeof adminSettingsRouteRouteWithChildren
  '/api/image-preview': typeof ApiImagePreviewRoute
  '/login/auth-check': typeof LoginAuthCheckRoute
  '/(admin)/': typeof adminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/(admin)/$orgId/tasks': typeof adminOrgIdTasksRouteRouteWithChildren
  '/(admin)/settings/connections': typeof adminSettingsConnectionsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(admin)/$orgId/': typeof adminOrgIdIndexRoute
  '/(admin)/console/': typeof adminConsoleIndexRoute
  '/(admin)/mine/': typeof adminMineIndexRoute
  '/(admin)/settings/': typeof adminSettingsIndexRoute
  '/invite/$orgId/': typeof InviteOrgIdIndexRoute
  '/orgs/$orgSlug/': typeof OrgsOrgSlugIndexRoute
  '/(admin)/$orgId/tasks/$taskShortId': typeof adminOrgIdTasksTaskShortIdRouteRouteWithChildren
  '/(admin)/settings/org/$orgId': typeof adminSettingsOrgOrgIdRouteRouteWithChildren
  '/(admin)/$orgId/tasks/': typeof adminOrgIdTasksIndexRoute
  '/(admin)/console/connections/': typeof adminConsoleConnectionsIndexRoute
  '/(admin)/settings/connections/': typeof adminSettingsConnectionsIndexRoute
  '/(admin)/$orgId/tasks/$taskShortId/': typeof adminOrgIdTasksTaskShortIdIndexRoute
  '/(admin)/settings/org/$orgId/': typeof adminSettingsOrgOrgIdIndexRoute
  '/(admin)/settings/org/$orgId/teams/new': typeof adminSettingsOrgOrgIdTeamsNewRoute
  '/(admin)/settings/org/$orgId/categories/': typeof adminSettingsOrgOrgIdCategoriesIndexRoute
  '/(admin)/settings/org/$orgId/connections/': typeof adminSettingsOrgOrgIdConnectionsIndexRoute
  '/(admin)/settings/org/$orgId/labels/': typeof adminSettingsOrgOrgIdLabelsIndexRoute
  '/(admin)/settings/org/$orgId/members/': typeof adminSettingsOrgOrgIdMembersIndexRoute
  '/(admin)/settings/org/$orgId/teams/': typeof adminSettingsOrgOrgIdTeamsIndexRoute
  '/(admin)/settings/org/$orgId/templates/': typeof adminSettingsOrgOrgIdTemplatesIndexRoute
  '/(admin)/settings/org/$orgId/views/': typeof adminSettingsOrgOrgIdViewsIndexRoute
  '/(admin)/settings/org/$orgId/connections/$connectionId/': typeof adminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute
  '/(admin)/settings/org/$orgId/teams/$teamId/': typeof adminSettingsOrgOrgIdTeamsTeamIdIndexRoute
  '/(admin)/settings/org/$orgId/views/$viewId/': typeof adminSettingsOrgOrgIdViewsViewIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/manifest.webmanifest'
    | '/prosekit-test'
    | '/$orgId'
    | '/mine'
    | '/settings'
    | '/api/image-preview'
    | '/login/auth-check'
    | '/'
    | '/login'
    | '/$orgId/tasks'
    | '/settings/connections'
    | '/api/auth/$'
    | '/$orgId/'
    | '/console'
    | '/mine/'
    | '/settings/'
    | '/invite/$orgId'
    | '/orgs/$orgSlug'
    | '/$orgId/tasks/$taskShortId'
    | '/settings/org/$orgId'
    | '/$orgId/tasks/'
    | '/console/connections'
    | '/settings/connections/'
    | '/$orgId/tasks/$taskShortId/'
    | '/settings/org/$orgId/'
    | '/settings/org/$orgId/teams/new'
    | '/settings/org/$orgId/categories'
    | '/settings/org/$orgId/connections'
    | '/settings/org/$orgId/labels'
    | '/settings/org/$orgId/members'
    | '/settings/org/$orgId/teams'
    | '/settings/org/$orgId/templates'
    | '/settings/org/$orgId/views'
    | '/settings/org/$orgId/connections/$connectionId'
    | '/settings/org/$orgId/teams/$teamId'
    | '/settings/org/$orgId/views/$viewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/manifest.webmanifest'
    | '/prosekit-test'
    | '/api/image-preview'
    | '/login/auth-check'
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/$orgId'
    | '/console'
    | '/mine'
    | '/settings'
    | '/invite/$orgId'
    | '/orgs/$orgSlug'
    | '/$orgId/tasks'
    | '/console/connections'
    | '/settings/connections'
    | '/$orgId/tasks/$taskShortId'
    | '/settings/org/$orgId'
    | '/settings/org/$orgId/teams/new'
    | '/settings/org/$orgId/categories'
    | '/settings/org/$orgId/connections'
    | '/settings/org/$orgId/labels'
    | '/settings/org/$orgId/members'
    | '/settings/org/$orgId/teams'
    | '/settings/org/$orgId/templates'
    | '/settings/org/$orgId/views'
    | '/settings/org/$orgId/connections/$connectionId'
    | '/settings/org/$orgId/teams/$teamId'
    | '/settings/org/$orgId/views/$viewId'
  id:
    | '__root__'
    | '/(admin)'
    | '/manifest.webmanifest'
    | '/prosekit-test'
    | '/(admin)/$orgId'
    | '/(admin)/mine'
    | '/(admin)/settings'
    | '/api/image-preview'
    | '/login/auth-check'
    | '/(admin)/'
    | '/login/'
    | '/(admin)/$orgId/tasks'
    | '/(admin)/settings/connections'
    | '/api/auth/$'
    | '/(admin)/$orgId/'
    | '/(admin)/console/'
    | '/(admin)/mine/'
    | '/(admin)/settings/'
    | '/invite/$orgId/'
    | '/orgs/$orgSlug/'
    | '/(admin)/$orgId/tasks/$taskShortId'
    | '/(admin)/settings/org/$orgId'
    | '/(admin)/$orgId/tasks/'
    | '/(admin)/console/connections/'
    | '/(admin)/settings/connections/'
    | '/(admin)/$orgId/tasks/$taskShortId/'
    | '/(admin)/settings/org/$orgId/'
    | '/(admin)/settings/org/$orgId/teams/new'
    | '/(admin)/settings/org/$orgId/categories/'
    | '/(admin)/settings/org/$orgId/connections/'
    | '/(admin)/settings/org/$orgId/labels/'
    | '/(admin)/settings/org/$orgId/members/'
    | '/(admin)/settings/org/$orgId/teams/'
    | '/(admin)/settings/org/$orgId/templates/'
    | '/(admin)/settings/org/$orgId/views/'
    | '/(admin)/settings/org/$orgId/connections/$connectionId/'
    | '/(admin)/settings/org/$orgId/teams/$teamId/'
    | '/(admin)/settings/org/$orgId/views/$viewId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminRouteRoute: typeof adminRouteRouteWithChildren
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  ProsekitTestRoute: typeof ProsekitTestRoute
  ApiImagePreviewRoute: typeof ApiImagePreviewRoute
  LoginAuthCheckRoute: typeof LoginAuthCheckRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  InviteOrgIdIndexRoute: typeof InviteOrgIdIndexRoute
  OrgsOrgSlugIndexRoute: typeof OrgsOrgSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prosekit-test': {
      id: '/prosekit-test'
      path: '/prosekit-test'
      fullPath: '/prosekit-test'
      preLoaderRoute: typeof ProsekitTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/': {
      id: '/(admin)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof adminIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/login/auth-check': {
      id: '/login/auth-check'
      path: '/login/auth-check'
      fullPath: '/login/auth-check'
      preLoaderRoute: typeof LoginAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-preview': {
      id: '/api/image-preview'
      path: '/api/image-preview'
      fullPath: '/api/image-preview'
      preLoaderRoute: typeof ApiImagePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/settings': {
      id: '/(admin)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof adminSettingsRouteRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/mine': {
      id: '/(admin)/mine'
      path: '/mine'
      fullPath: '/mine'
      preLoaderRoute: typeof adminMineRouteRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/$orgId': {
      id: '/(admin)/$orgId'
      path: '/$orgId'
      fullPath: '/$orgId'
      preLoaderRoute: typeof adminOrgIdRouteRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/orgs/$orgSlug/': {
      id: '/orgs/$orgSlug/'
      path: '/orgs/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof OrgsOrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$orgId/': {
      id: '/invite/$orgId/'
      path: '/invite/$orgId'
      fullPath: '/invite/$orgId'
      preLoaderRoute: typeof InviteOrgIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/settings/': {
      id: '/(admin)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof adminSettingsIndexRouteImport
      parentRoute: typeof adminSettingsRouteRoute
    }
    '/(admin)/mine/': {
      id: '/(admin)/mine/'
      path: '/'
      fullPath: '/mine/'
      preLoaderRoute: typeof adminMineIndexRouteImport
      parentRoute: typeof adminMineRouteRoute
    }
    '/(admin)/console/': {
      id: '/(admin)/console/'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof adminConsoleIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/$orgId/': {
      id: '/(admin)/$orgId/'
      path: '/'
      fullPath: '/$orgId/'
      preLoaderRoute: typeof adminOrgIdIndexRouteImport
      parentRoute: typeof adminOrgIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/settings/connections': {
      id: '/(admin)/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof adminSettingsConnectionsRouteRouteImport
      parentRoute: typeof adminSettingsRouteRoute
    }
    '/(admin)/$orgId/tasks': {
      id: '/(admin)/$orgId/tasks'
      path: '/tasks'
      fullPath: '/$orgId/tasks'
      preLoaderRoute: typeof adminOrgIdTasksRouteRouteImport
      parentRoute: typeof adminOrgIdRouteRoute
    }
    '/(admin)/settings/connections/': {
      id: '/(admin)/settings/connections/'
      path: '/'
      fullPath: '/settings/connections/'
      preLoaderRoute: typeof adminSettingsConnectionsIndexRouteImport
      parentRoute: typeof adminSettingsConnectionsRouteRoute
    }
    '/(admin)/console/connections/': {
      id: '/(admin)/console/connections/'
      path: '/console/connections'
      fullPath: '/console/connections'
      preLoaderRoute: typeof adminConsoleConnectionsIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/$orgId/tasks/': {
      id: '/(admin)/$orgId/tasks/'
      path: '/'
      fullPath: '/$orgId/tasks/'
      preLoaderRoute: typeof adminOrgIdTasksIndexRouteImport
      parentRoute: typeof adminOrgIdTasksRouteRoute
    }
    '/(admin)/settings/org/$orgId': {
      id: '/(admin)/settings/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/settings/org/$orgId'
      preLoaderRoute: typeof adminSettingsOrgOrgIdRouteRouteImport
      parentRoute: typeof adminSettingsRouteRoute
    }
    '/(admin)/$orgId/tasks/$taskShortId': {
      id: '/(admin)/$orgId/tasks/$taskShortId'
      path: '/$taskShortId'
      fullPath: '/$orgId/tasks/$taskShortId'
      preLoaderRoute: typeof adminOrgIdTasksTaskShortIdRouteRouteImport
      parentRoute: typeof adminOrgIdTasksRouteRoute
    }
    '/(admin)/settings/org/$orgId/': {
      id: '/(admin)/settings/org/$orgId/'
      path: '/'
      fullPath: '/settings/org/$orgId/'
      preLoaderRoute: typeof adminSettingsOrgOrgIdIndexRouteImport
      parentRoute: typeof adminSettingsOrgOrgIdRouteRoute
    }
    '/(admin)/$orgId/tasks/$taskShortId/': {
      id: '/(admin)/$orgId/tasks/$taskShortId/'
      path: '/'
      fullPath: '/$orgId/tasks/$taskShortId/'
      preLoaderRoute: typeof adminOrgIdTasksTaskShortIdIndexRouteImport
      parentRoute: typeof adminOrgIdTasksTaskShortIdRouteRoute
    }
    '/(admin)/settings/org/$orgId/views/': {
      id: '/(admin)/settings/org/$orgId/views/'
      path: '/views'
      fullPath: '/settings/org/$orgId/views'
      preLoaderRoute: typeof adminSettingsOrgOrgIdViewsIndexRouteImport
      parentRoute: typeof adminSettingsOrgOrgIdRouteRoute
    }
    '/(admin)/settings/org/$orgId/templates/': {
      id: '/(admin)/settings/org/$orgId/templates/'
      path: '/templates'
      fullPath: '/settings/org/$orgId/templates'
      preLoaderRoute: typeof adminSettingsOrgOrgIdTemplatesIndexRouteImport
      parentRoute: typeof adminSettingsOrgOrgIdRouteRoute
    }
    '/(admin)/settings/org/$orgId/teams/': {
      id: '/(admin)/settings/org/$orgId/teams/'
      path: '/teams'
      fullPath: '/settings/org/$orgId/teams'
      preLoaderRoute: typeof adminSettingsOrgOrgIdTeamsIndexRouteImport
      parentRoute: typeof adminSettingsOrgOrgIdRouteRoute
    }
    '/(admin)/settings/org/$orgId/members/': {
      id: '/(admin)/settings/org/$orgId/members/'
      path: '/members'
      fullPath: '/settings/org/$orgId/members'
      preLoaderRoute: typeof adminSettingsOrgOrgIdMembersIndexRouteImport
      parentRoute: typeof adminSettingsOrgOrgIdRouteRoute
    }
    '/(admin)/settings/org/$orgId/labels/': {
      id: '/(admin)/settings/org/$orgId/labels/'
      path: '/labels'
      fullPath: '/settings/org/$orgId/labels'
      preLoaderRoute: typeof adminSettingsOrgOrgIdLabelsIndexRouteImport
      parentRoute: typeof adminSettingsOrgOrgIdRouteRoute
    }
    '/(admin)/settings/org/$orgId/connections/': {
      id: '/(admin)/settings/org/$orgId/connections/'
      path: '/connections'
      fullPath: '/settings/org/$orgId/connections'
      preLoaderRoute: typeof adminSettingsOrgOrgIdConnectionsIndexRouteImport
      parentRoute: typeof adminSettingsOrgOrgIdRouteRoute
    }
    '/(admin)/settings/org/$orgId/categories/': {
      id: '/(admin)/settings/org/$orgId/categories/'
      path: '/categories'
      fullPath: '/settings/org/$orgId/categories'
      preLoaderRoute: typeof adminSettingsOrgOrgIdCategoriesIndexRouteImport
      parentRoute: typeof adminSettingsOrgOrgIdRouteRoute
    }
    '/(admin)/settings/org/$orgId/teams/new': {
      id: '/(admin)/settings/org/$orgId/teams/new'
      path: '/teams/new'
      fullPath: '/settings/org/$orgId/teams/new'
      preLoaderRoute: typeof adminSettingsOrgOrgIdTeamsNewRouteImport
      parentRoute: typeof adminSettingsOrgOrgIdRouteRoute
    }
    '/(admin)/settings/org/$orgId/views/$viewId/': {
      id: '/(admin)/settings/org/$orgId/views/$viewId/'
      path: '/views/$viewId'
      fullPath: '/settings/org/$orgId/views/$viewId'
      preLoaderRoute: typeof adminSettingsOrgOrgIdViewsViewIdIndexRouteImport
      parentRoute: typeof adminSettingsOrgOrgIdRouteRoute
    }
    '/(admin)/settings/org/$orgId/teams/$teamId/': {
      id: '/(admin)/settings/org/$orgId/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/settings/org/$orgId/teams/$teamId'
      preLoaderRoute: typeof adminSettingsOrgOrgIdTeamsTeamIdIndexRouteImport
      parentRoute: typeof adminSettingsOrgOrgIdRouteRoute
    }
    '/(admin)/settings/org/$orgId/connections/$connectionId/': {
      id: '/(admin)/settings/org/$orgId/connections/$connectionId/'
      path: '/connections/$connectionId'
      fullPath: '/settings/org/$orgId/connections/$connectionId'
      preLoaderRoute: typeof adminSettingsOrgOrgIdConnectionsConnectionIdIndexRouteImport
      parentRoute: typeof adminSettingsOrgOrgIdRouteRoute
    }
  }
}

interface adminOrgIdTasksTaskShortIdRouteRouteChildren {
  adminOrgIdTasksTaskShortIdIndexRoute: typeof adminOrgIdTasksTaskShortIdIndexRoute
}

const adminOrgIdTasksTaskShortIdRouteRouteChildren: adminOrgIdTasksTaskShortIdRouteRouteChildren =
  {
    adminOrgIdTasksTaskShortIdIndexRoute: adminOrgIdTasksTaskShortIdIndexRoute,
  }

const adminOrgIdTasksTaskShortIdRouteRouteWithChildren =
  adminOrgIdTasksTaskShortIdRouteRoute._addFileChildren(
    adminOrgIdTasksTaskShortIdRouteRouteChildren,
  )

interface adminOrgIdTasksRouteRouteChildren {
  adminOrgIdTasksTaskShortIdRouteRoute: typeof adminOrgIdTasksTaskShortIdRouteRouteWithChildren
  adminOrgIdTasksIndexRoute: typeof adminOrgIdTasksIndexRoute
}

const adminOrgIdTasksRouteRouteChildren: adminOrgIdTasksRouteRouteChildren = {
  adminOrgIdTasksTaskShortIdRouteRoute:
    adminOrgIdTasksTaskShortIdRouteRouteWithChildren,
  adminOrgIdTasksIndexRoute: adminOrgIdTasksIndexRoute,
}

const adminOrgIdTasksRouteRouteWithChildren =
  adminOrgIdTasksRouteRoute._addFileChildren(adminOrgIdTasksRouteRouteChildren)

interface adminOrgIdRouteRouteChildren {
  adminOrgIdTasksRouteRoute: typeof adminOrgIdTasksRouteRouteWithChildren
  adminOrgIdIndexRoute: typeof adminOrgIdIndexRoute
}

const adminOrgIdRouteRouteChildren: adminOrgIdRouteRouteChildren = {
  adminOrgIdTasksRouteRoute: adminOrgIdTasksRouteRouteWithChildren,
  adminOrgIdIndexRoute: adminOrgIdIndexRoute,
}

const adminOrgIdRouteRouteWithChildren = adminOrgIdRouteRoute._addFileChildren(
  adminOrgIdRouteRouteChildren,
)

interface adminMineRouteRouteChildren {
  adminMineIndexRoute: typeof adminMineIndexRoute
}

const adminMineRouteRouteChildren: adminMineRouteRouteChildren = {
  adminMineIndexRoute: adminMineIndexRoute,
}

const adminMineRouteRouteWithChildren = adminMineRouteRoute._addFileChildren(
  adminMineRouteRouteChildren,
)

interface adminSettingsConnectionsRouteRouteChildren {
  adminSettingsConnectionsIndexRoute: typeof adminSettingsConnectionsIndexRoute
}

const adminSettingsConnectionsRouteRouteChildren: adminSettingsConnectionsRouteRouteChildren =
  {
    adminSettingsConnectionsIndexRoute: adminSettingsConnectionsIndexRoute,
  }

const adminSettingsConnectionsRouteRouteWithChildren =
  adminSettingsConnectionsRouteRoute._addFileChildren(
    adminSettingsConnectionsRouteRouteChildren,
  )

interface adminSettingsOrgOrgIdRouteRouteChildren {
  adminSettingsOrgOrgIdIndexRoute: typeof adminSettingsOrgOrgIdIndexRoute
  adminSettingsOrgOrgIdTeamsNewRoute: typeof adminSettingsOrgOrgIdTeamsNewRoute
  adminSettingsOrgOrgIdCategoriesIndexRoute: typeof adminSettingsOrgOrgIdCategoriesIndexRoute
  adminSettingsOrgOrgIdConnectionsIndexRoute: typeof adminSettingsOrgOrgIdConnectionsIndexRoute
  adminSettingsOrgOrgIdLabelsIndexRoute: typeof adminSettingsOrgOrgIdLabelsIndexRoute
  adminSettingsOrgOrgIdMembersIndexRoute: typeof adminSettingsOrgOrgIdMembersIndexRoute
  adminSettingsOrgOrgIdTeamsIndexRoute: typeof adminSettingsOrgOrgIdTeamsIndexRoute
  adminSettingsOrgOrgIdTemplatesIndexRoute: typeof adminSettingsOrgOrgIdTemplatesIndexRoute
  adminSettingsOrgOrgIdViewsIndexRoute: typeof adminSettingsOrgOrgIdViewsIndexRoute
  adminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute: typeof adminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute
  adminSettingsOrgOrgIdTeamsTeamIdIndexRoute: typeof adminSettingsOrgOrgIdTeamsTeamIdIndexRoute
  adminSettingsOrgOrgIdViewsViewIdIndexRoute: typeof adminSettingsOrgOrgIdViewsViewIdIndexRoute
}

const adminSettingsOrgOrgIdRouteRouteChildren: adminSettingsOrgOrgIdRouteRouteChildren =
  {
    adminSettingsOrgOrgIdIndexRoute: adminSettingsOrgOrgIdIndexRoute,
    adminSettingsOrgOrgIdTeamsNewRoute: adminSettingsOrgOrgIdTeamsNewRoute,
    adminSettingsOrgOrgIdCategoriesIndexRoute:
      adminSettingsOrgOrgIdCategoriesIndexRoute,
    adminSettingsOrgOrgIdConnectionsIndexRoute:
      adminSettingsOrgOrgIdConnectionsIndexRoute,
    adminSettingsOrgOrgIdLabelsIndexRoute:
      adminSettingsOrgOrgIdLabelsIndexRoute,
    adminSettingsOrgOrgIdMembersIndexRoute:
      adminSettingsOrgOrgIdMembersIndexRoute,
    adminSettingsOrgOrgIdTeamsIndexRoute: adminSettingsOrgOrgIdTeamsIndexRoute,
    adminSettingsOrgOrgIdTemplatesIndexRoute:
      adminSettingsOrgOrgIdTemplatesIndexRoute,
    adminSettingsOrgOrgIdViewsIndexRoute: adminSettingsOrgOrgIdViewsIndexRoute,
    adminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute:
      adminSettingsOrgOrgIdConnectionsConnectionIdIndexRoute,
    adminSettingsOrgOrgIdTeamsTeamIdIndexRoute:
      adminSettingsOrgOrgIdTeamsTeamIdIndexRoute,
    adminSettingsOrgOrgIdViewsViewIdIndexRoute:
      adminSettingsOrgOrgIdViewsViewIdIndexRoute,
  }

const adminSettingsOrgOrgIdRouteRouteWithChildren =
  adminSettingsOrgOrgIdRouteRoute._addFileChildren(
    adminSettingsOrgOrgIdRouteRouteChildren,
  )

interface adminSettingsRouteRouteChildren {
  adminSettingsConnectionsRouteRoute: typeof adminSettingsConnectionsRouteRouteWithChildren
  adminSettingsIndexRoute: typeof adminSettingsIndexRoute
  adminSettingsOrgOrgIdRouteRoute: typeof adminSettingsOrgOrgIdRouteRouteWithChildren
}

const adminSettingsRouteRouteChildren: adminSettingsRouteRouteChildren = {
  adminSettingsConnectionsRouteRoute:
    adminSettingsConnectionsRouteRouteWithChildren,
  adminSettingsIndexRoute: adminSettingsIndexRoute,
  adminSettingsOrgOrgIdRouteRoute: adminSettingsOrgOrgIdRouteRouteWithChildren,
}

const adminSettingsRouteRouteWithChildren =
  adminSettingsRouteRoute._addFileChildren(adminSettingsRouteRouteChildren)

interface adminRouteRouteChildren {
  adminOrgIdRouteRoute: typeof adminOrgIdRouteRouteWithChildren
  adminMineRouteRoute: typeof adminMineRouteRouteWithChildren
  adminSettingsRouteRoute: typeof adminSettingsRouteRouteWithChildren
  adminIndexRoute: typeof adminIndexRoute
  adminConsoleIndexRoute: typeof adminConsoleIndexRoute
  adminConsoleConnectionsIndexRoute: typeof adminConsoleConnectionsIndexRoute
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminOrgIdRouteRoute: adminOrgIdRouteRouteWithChildren,
  adminMineRouteRoute: adminMineRouteRouteWithChildren,
  adminSettingsRouteRoute: adminSettingsRouteRouteWithChildren,
  adminIndexRoute: adminIndexRoute,
  adminConsoleIndexRoute: adminConsoleIndexRoute,
  adminConsoleConnectionsIndexRoute: adminConsoleConnectionsIndexRoute,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminRouteRoute: adminRouteRouteWithChildren,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  ProsekitTestRoute: ProsekitTestRoute,
  ApiImagePreviewRoute: ApiImagePreviewRoute,
  LoginAuthCheckRoute: LoginAuthCheckRoute,
  LoginIndexRoute: LoginIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  InviteOrgIdIndexRoute: InviteOrgIdIndexRoute,
  OrgsOrgSlugIndexRoute: OrgsOrgSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
