/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'
import { Route as DocsLlmsDottxtRouteImport } from './routes/docs/llms[.]txt'
import { Route as DocsLlmsFullDottxtRouteImport } from './routes/docs/llms-full[.]txt'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiOpenapiProxyRouteImport } from './routes/api/openapi-proxy'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as MarketingLegalTermsRouteImport } from './routes/_marketing/legal/terms'
import { Route as MarketingLegalSubprocessorsRouteImport } from './routes/_marketing/legal/subprocessors'
import { Route as MarketingLegalPrivacyRouteImport } from './routes/_marketing/legal/privacy'
import { Route as MarketingFeaturesSlugRouteImport } from './routes/_marketing/features/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLlmsDottxtRoute = DocsLlmsDottxtRouteImport.update({
  id: '/docs/llms.txt',
  path: '/docs/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLlmsFullDottxtRoute = DocsLlmsFullDottxtRouteImport.update({
  id: '/docs/llms-full.txt',
  path: '/docs/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiProxyRoute = ApiOpenapiProxyRouteImport.update({
  id: '/api/openapi-proxy',
  path: '/api/openapi-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLegalTermsRoute = MarketingLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLegalSubprocessorsRoute =
  MarketingLegalSubprocessorsRouteImport.update({
    id: '/legal/subprocessors',
    path: '/legal/subprocessors',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLegalPrivacyRoute = MarketingLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesSlugRoute = MarketingFeaturesSlugRouteImport.update({
  id: '/features/$slug',
  path: '/features/$slug',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/pricing': typeof MarketingPricingRoute
  '/api/og': typeof ApiOgRoute
  '/api/openapi-proxy': typeof ApiOpenapiProxyRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms-full.txt': typeof DocsLlmsFullDottxtRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/features/$slug': typeof MarketingFeaturesSlugRoute
  '/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/legal/subprocessors': typeof MarketingLegalSubprocessorsRoute
  '/legal/terms': typeof MarketingLegalTermsRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/pricing': typeof MarketingPricingRoute
  '/api/og': typeof ApiOgRoute
  '/api/openapi-proxy': typeof ApiOpenapiProxyRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms-full.txt': typeof DocsLlmsFullDottxtRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/': typeof MarketingIndexRoute
  '/features/$slug': typeof MarketingFeaturesSlugRoute
  '/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/legal/subprocessors': typeof MarketingLegalSubprocessorsRoute
  '/legal/terms': typeof MarketingLegalTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/api/og': typeof ApiOgRoute
  '/api/openapi-proxy': typeof ApiOpenapiProxyRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms-full.txt': typeof DocsLlmsFullDottxtRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/features/$slug': typeof MarketingFeaturesSlugRoute
  '/_marketing/legal/privacy': typeof MarketingLegalPrivacyRoute
  '/_marketing/legal/subprocessors': typeof MarketingLegalSubprocessorsRoute
  '/_marketing/legal/terms': typeof MarketingLegalTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/pricing'
    | '/api/og'
    | '/api/openapi-proxy'
    | '/api/search'
    | '/docs/$'
    | '/docs/llms-full.txt'
    | '/docs/llms.txt'
    | '/docs/{$}.md'
    | '/features/$slug'
    | '/legal/privacy'
    | '/legal/subprocessors'
    | '/legal/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/pricing'
    | '/api/og'
    | '/api/openapi-proxy'
    | '/api/search'
    | '/docs/$'
    | '/docs/llms-full.txt'
    | '/docs/llms.txt'
    | '/docs/{$}.md'
    | '/'
    | '/features/$slug'
    | '/legal/privacy'
    | '/legal/subprocessors'
    | '/legal/terms'
  id:
    | '__root__'
    | '/_marketing'
    | '/sitemap.xml'
    | '/_marketing/pricing'
    | '/api/og'
    | '/api/openapi-proxy'
    | '/api/search'
    | '/docs/$'
    | '/docs/llms-full.txt'
    | '/docs/llms.txt'
    | '/docs/{$}.md'
    | '/_marketing/'
    | '/_marketing/features/$slug'
    | '/_marketing/legal/privacy'
    | '/_marketing/legal/subprocessors'
    | '/_marketing/legal/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiOpenapiProxyRoute: typeof ApiOpenapiProxyRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsLlmsFullDottxtRoute: typeof DocsLlmsFullDottxtRoute
  DocsLlmsDottxtRoute: typeof DocsLlmsDottxtRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/llms.txt': {
      id: '/docs/llms.txt'
      path: '/docs/llms.txt'
      fullPath: '/docs/llms.txt'
      preLoaderRoute: typeof DocsLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/llms-full.txt': {
      id: '/docs/llms-full.txt'
      path: '/docs/llms-full.txt'
      fullPath: '/docs/llms-full.txt'
      preLoaderRoute: typeof DocsLlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi-proxy': {
      id: '/api/openapi-proxy'
      path: '/api/openapi-proxy'
      fullPath: '/api/openapi-proxy'
      preLoaderRoute: typeof ApiOpenapiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/legal/terms': {
      id: '/_marketing/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof MarketingLegalTermsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/legal/subprocessors': {
      id: '/_marketing/legal/subprocessors'
      path: '/legal/subprocessors'
      fullPath: '/legal/subprocessors'
      preLoaderRoute: typeof MarketingLegalSubprocessorsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/legal/privacy': {
      id: '/_marketing/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof MarketingLegalPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/$slug': {
      id: '/_marketing/features/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof MarketingFeaturesSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingFeaturesSlugRoute: typeof MarketingFeaturesSlugRoute
  MarketingLegalPrivacyRoute: typeof MarketingLegalPrivacyRoute
  MarketingLegalSubprocessorsRoute: typeof MarketingLegalSubprocessorsRoute
  MarketingLegalTermsRoute: typeof MarketingLegalTermsRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingFeaturesSlugRoute: MarketingFeaturesSlugRoute,
  MarketingLegalPrivacyRoute: MarketingLegalPrivacyRoute,
  MarketingLegalSubprocessorsRoute: MarketingLegalSubprocessorsRoute,
  MarketingLegalTermsRoute: MarketingLegalTermsRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiOgRoute: ApiOgRoute,
  ApiOpenapiProxyRoute: ApiOpenapiProxyRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsLlmsFullDottxtRoute: DocsLlmsFullDottxtRoute,
  DocsLlmsDottxtRoute: DocsLlmsDottxtRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
