name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      start:
        description: "Deploy start (frontend)"
        type: boolean
        default: true
      backend:
        description: "Deploy backend"
        type: boolean
        default: true
      worker:
        description: "Deploy worker"
        type: boolean
        default: true
      traefik:
        description: "Deploy traefik"
        type: boolean
        default: true
      marketing:
        description: "Deploy marketing"
        type: boolean
        default: true
      platform_amd64:
        description: "Build linux/amd64"
        type: boolean
        default: true
      platform_arm64:
        description: "Build linux/arm64"
        type: boolean
        default: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: staging

jobs:
  define-matrix:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    outputs:
      apps: ${{ steps.set-matrix.outputs.apps }}
      platforms: ${{ steps.set-matrix.outputs.platforms }}
    steps:
      - id: set-matrix
        run: |
          apps="[]"
          if [[ "${{ inputs.start }}" == "true" ]]; then
            apps=$(echo $apps | jq '. + ["start"]')
          fi
          if [[ "${{ inputs.backend }}" == "true" ]]; then
            apps=$(echo $apps | jq '. + ["backend"]')
          fi
          if [[ "${{ inputs.worker }}" == "true" ]]; then
            apps=$(echo $apps | jq '. + ["worker"]')
          fi
          if [[ "${{ inputs.traefik }}" == "true" ]]; then
            apps=$(echo $apps | jq '. + ["traefik"]')
          fi
          if [[ "${{ inputs.marketing }}" == "true" ]]; then
            apps=$(echo $apps | jq '. + ["marketing"]')
          fi
          echo "apps=$(echo $apps | jq -c .)" >> $GITHUB_OUTPUT

          platforms="[]"
          if [[ "${{ inputs.platform_amd64 }}" == "true" ]]; then
            platforms=$(echo $platforms | jq '. + ["linux/amd64"]')
          fi
          if [[ "${{ inputs.platform_arm64 }}" == "true" ]]; then
            platforms=$(echo $platforms | jq '. + ["linux/arm64"]')
          fi
          echo "platforms=$(echo $platforms | jq -c .)" >> $GITHUB_OUTPUT

  build-image:
    needs: define-matrix
    if: needs.define-matrix.outputs.apps != '[]' && needs.define-matrix.outputs.platforms != '[]'
    name: Build and Push
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'blacksmith-4vcpu-ubuntu-2404-arm' || 'blacksmith-4vcpu-ubuntu-2404' }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJson(needs.define-matrix.outputs.apps) }}
        platform: ${{ fromJson(needs.define-matrix.outputs.platforms) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Docker Config
        id: config
        run: |
          if [[ "${{ matrix.app }}" == "start" ]]; then
            echo "dockerfile=./apps/start/Dockerfile" >> $GITHUB_OUTPUT
            echo "image_suffix=-start" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.app }}" == "backend" ]]; then
            echo "dockerfile=./apps/backend/Dockerfile" >> $GITHUB_OUTPUT
            echo "image_suffix=-backend" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.app }}" == "worker" ]]; then
            echo "dockerfile=./apps/worker/Dockerfile" >> $GITHUB_OUTPUT
            echo "image_suffix=-worker" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.app }}" == "traefik" ]]; then
            echo "dockerfile=./apps/traefik/Dockerfile" >> $GITHUB_OUTPUT
            echo "image_suffix=-traefik" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.app }}" == "marketing" ]]; then
            echo "dockerfile=./apps/marketing/Dockerfile" >> $GITHUB_OUTPUT
            echo "image_suffix=-marketing" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Builder
        uses: useblacksmith/setup-docker-builder@v1
        with:
          platforms: ${{ matrix.platform }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ steps.config.outputs.image_suffix }}
          tags: |
            type=raw,value=${{ env.TAG }}
            type=raw,value=${{ env.TAG }}-${{ github.sha }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ steps.config.outputs.dockerfile }}
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ steps.config.outputs.image_suffix }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.app }}-${{ strategy.job-index }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge-manifest:
    needs: [define-matrix, build-image]
    if: needs.define-matrix.outputs.apps != '[]' && needs.define-matrix.outputs.platforms != '[]'
    runs-on: blacksmith-2vcpu-ubuntu-2404
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJson(needs.define-matrix.outputs.apps) }}
    steps:
      - name: Determine Docker Config
        id: config
        run: |
          if [[ "${{ matrix.app }}" == "start" ]]; then
            echo "image_suffix=-start" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.app }}" == "backend" ]]; then
            echo "image_suffix=-backend" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.app }}" == "worker" ]]; then
            echo "image_suffix=-worker" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.app }}" == "traefik" ]]; then
            echo "image_suffix=-traefik" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.app }}" == "marketing" ]]; then
            echo "image_suffix=-marketing" >> $GITHUB_OUTPUT
          fi

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          pattern: digests-${{ matrix.app }}-*
          merge-multiple: true
          path: /tmp/digests

      - name: Set up Docker Builder
        uses: useblacksmith/setup-docker-builder@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ steps.config.outputs.image_suffix }}
          tags: |
            type=raw,value=${{ env.TAG }}
            type=raw,value=${{ env.TAG }}-${{ github.sha }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ steps.config.outputs.image_suffix }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{ steps.config.outputs.image_suffix }}:${{ env.TAG }}
